// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"github.com/karolhrdina/misc/hw/model/ports"
	"github.com/karolhrdina/misc/hw/pb.go"
	"github.com/karolhrdina/misc/hw/pkg/env"
	"github.com/karolhrdina/misc/hw/pkg/storer"
	"github.com/karolhrdina/misc/hw/services/client-api/handlers"
	"google.golang.org/grpc"
)

// Injectors from initialize.go:

func initializeService() (*Service, error) {
	portsV1 := handlers.NewV1PortsImportAPI()
	portdomainClient := providePortDomainClient()
	storer := provideStorer(portdomainClient)
	service := NewService(portsV1, storer)
	return service, nil
}

// initialize.go:

func providePortDomainClient() pb_go.PortdomainClient {
	addr := env.GetVar("PORTDOMAIN_GRPC_ADDR", ":9082")
	c, err := grpc.Dial(addr, grpc.WithInsecure())
	if err != nil {
		panic(err)
	}
	return pb_go.NewPortdomainClient(c)
}

func provideStorer(client pb_go.PortdomainClient) ports.Storer {
	return storer.NewGRPCStorer(client)
}
