// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/karolhrdina/misc/hw/pkg/db"
)

// Injectors from initialize.go:

func initializeService() (*Service, error) {
	sqlDB, err := db.ProvidePG()
	if err != nil {
		return nil, err
	}
	service := NewService(sqlDB)
	return service, nil
}
