// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"database/sql"
	"github.com/karolhrdina/misc/hw/model/ports"
	"github.com/karolhrdina/misc/hw/pkg/db"
	"github.com/karolhrdina/misc/hw/pkg/storer"
)

// Injectors from initialize.go:

func initializeService() (*Service, error) {
	sqlDB, err := db.ProvidePG()
	if err != nil {
		return nil, err
	}
	storer := provideStorer(sqlDB)
	service := NewService(sqlDB, storer)
	return service, nil
}

// initialize.go:

func provideStorer(db2 *sql.DB) ports.Storer {
	return storer.NewPostgresStorer(db2)
}
